Bug fix for ignore_prefix_files
https://github.com/conda/conda-build/pull/1008
causes a problem:

  File ...\\lib\\site-packages\\conda_build\\metadata.py, line 597, in ignore_prefix_files
    if any('\' in i for i in ret):
TypeError: 'bool' object is not iterable