Use py3.10 in test_pypi_installer_metadata
Build with python 3.9 recently started to fail because of dataclass(slots) which
is only available since 3.10.

```
  File "/tmp/pytest-of-xxx/pytest-36/test_pypi_installer_metadata0/imagesize_1780057243470/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
lacehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.9/site-packages/pip/_internal/models/scheme.py", line 13, in <module>
    @dataclass(frozen=True, slots=True)
TypeError: dataclass() got an unexpected keyword argument 'slots'
```