Always set filename, dirname for a machofile
This is required so that cf.uniqueness_key() doesn't error out with AttributeError:

patchelf: --print-rpath failed for
/opt/conda/conda-bld/cmake-binary_yyy/xxx/cmake-bin/share/cmake-3.9/Modules/CPack.OSXScriptLauncher.in
...
  File "/home/nwani/conda-build/conda_build/os_utils/pyldd.py", line 986, in _inspect_linkages_this
    return cf.uniqueness_key(), [], []
  File "/home/nwani/conda-build/conda_build/os_utils/pyldd.py", line 504, in uniqueness_key
    return self.filename
AttributeError: 'machofile' object has no attribute 'filename'