Fix in render.py::_read_specs_from_package
In A Travis’s PR job for Pull Request by Olivier (Scikit-Learn core maintainer, gh handle: ogrisel) to daal4py fails with conda build error:

https://github.com/IntelPython/daal4py/pull/111/checks?check_run_id=159357667

Failures manifest itself on Py2 on Linux, and Py 3 on OSX, i.e. work fine on Py3/Linux and Py2/OSX.
The failure happens during rendering of the recipe being built.

The trailing backtrace:

  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 234, in _read_specs_from_package
    if not specs and os.path.isfile(pkg_loc):
  File "/home/travis/miniconda/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

It appears as if the argument pkg_loc to _read_specs_from_package is None.

I suspect  that line 256, https://github.com/conda/conda-build/blob/master/conda_build/render.py#L256  should check that pkg_loc is not None:

if not specs and pkg_loc and os.path.isfile(pkg_loc):

Similar to how L244 does a block above.