Support anaconda.org upload for v1 recipes
This PR adds support for uploading v1 packages to anaconda.org channel
post build. It uses py-rattler's
[`upload_package_to_anaconda()`](https://rattler-build.prefix.dev/latest/py-rattler-build/reference/upload/#upload_package_to_anaconda) to
handle the upload.

To do this, `anaconda_token` and `user` settings need to be set in
`.condarc`.

We are using same logic as conda-build's handle_anaconda_upload()
function (i.e. upload if token and user values are detected and skip if
`--no-anaconda-upload` or `--build-only` are passed via CLI or set in
`.condarc`.

To test this PR; set the required `.condarc` settings with:

```
$ conda config --set anaconda_upload yes
$ conda config --set conda_build.anaconda_token <API_KEY>
$ conda config --set conda_build.user $username
```

Build a conda package with:

```
pytest-feedstock git:main $ conda-build recipe --quiet

(...)

Package upload was successful!: /home/jakov/miniforge3/conda-bld/noarch/pytest-9.0.3-pyh4616a5c_1.conda

=== Build summary ===
Tried to build 1 recipe file, resulting in 1 output.
1 succeeded, 0 failed.
```

To verify, search the given channel:

a) Before package build:
```
$ conda search jsmolic::pytest

No match found for: jsmolic::pytest. Search: jsmolic::*pytest*

PackagesNotFoundInChannelsError: The following packages are not available from current channels:

  - jsmolic::pytest
```

b) After package build:
```
$ conda search jsmolic::pytest

Loading channels: done
pytest                         9.0.3    pyh4616a5c_1  jsmolic
```

Closes: https://github.com/conda/conda-build/issues/5894